# Usa una imagen base de Node.js
FROM node:22.20-alpine

# Define la variable de entorno
ARG NEXT_PUBLIC_VERSION
ENV NEXT_PUBLIC_VERSION=$NEXT_PUBLIC_VERSION

# Instala las dependencias necesarias
RUN apk add --no-cache g++ make py3-pip bash nginx

# Crea un usuario y directorio para nginx
RUN adduser -D -g 'www' www
RUN mkdir /www
RUN chown -R www:www /var/lib/nginx /www

# Instala pnpm y pm2 globalmente
RUN npm --no-update-notifier --no-fund --global install pnpm@10.6.1 pm2

# Define el directorio de trabajo
WORKDIR /app

# Copia el contenido de tu aplicación al contenedor
COPY . /app
COPY var/docker/nginx.conf /etc/nginx/nginx.conf

# Instala las dependencias de tu proyecto
RUN pnpm install

# Compila tu aplicación
RUN NODE_OPTIONS="--max-old-space-size=4096" pnpm run build

# Comando para ejecutar nginx y pm2
CMD ["sh", "-c", "nginx && pnpm run pm2"]